swagger: "2.0"
info:
  title: myBlog API
  description: My Blog has a very cool swagger for API
  version: 1.0.0
  contact:
    email: kirk@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api/v1/posts
paths:
  /:
    post:
      tags:
      - myBlogBeeGo/controllersApiController
      description: create new post
      operationId: ApiController.CreatePost
      parameters:
      - in: body
        name: body
        description: json post body, use html body in double quotes instead {}
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      responses:
        "201":
          description: body is empty
        "500":
          description: body is empty
  /{id}:
    get:
      tags:
      - myBlogBeeGo/controllersApiController
      description: get one post
      operationId: ApiController.GetOnePost
      parameters:
      - in: path
        name: id
        description: ID of the post
        required: true
        type: string
      responses:
        "200":
          description: body is empty
        "404":
          description: not found
        "500":
          description: body is empty
    put:
      tags:
      - myBlogBeeGo/controllersApiController
      description: update post
      operationId: ApiController.UpdatePost
      parameters:
      - in: path
        name: id
        description: ID of the post
        required: true
        type: string
      - in: body
        name: body
        description: json post body, use html body in double quotes instead {}
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      responses:
        "200":
          description: body is empty
        "404":
          description: not found
        "500":
          description: body is empty
    delete:
      tags:
      - myBlogBeeGo/controllersApiController
      description: delete post
      operationId: ApiController.DeletePost
      parameters:
      - in: path
        name: id
        description: ID of the post
        required: true
        type: string
      responses:
        "200":
          description: body is empty
        "404":
          description: not found
        "500":
          description: body is empty
definitions:
  models.Post:
    title: Post
    type: object
    properties:
      body:
        $ref: '#/definitions/template.HTML'
      id:
        description: custom post id for create
        type: string
      summary:
        type: string
      title:
        type: string
  primitive.ObjectID:
    title: ObjectID
    type: object
  template.HTML:
    title: HTML
    type: object
tags:
- name: myBlogBeeGo/controllersApiController
  description: |
    ApiController for operations with posts via API.
